"""Capture session facts in a journal without asking an agent to maintain it.

A client end-of-session hook invokes this vendor-neutral script. It records the
branch, HEAD, commits since the previous capture, and uncommitted changes in an
append-only `.agent/journal/YYYY-MM-DD.md` block. The operation is idempotent:
when HEAD and the worktree have not changed, it writes nothing. The code records
facts only and never invents semantic state such as a next step.

This module is vendored support code derived from a generic session-capture
implementation; it contains no private-project provenance.
"""
from __future__ import annotations

import subprocess
import sys
from datetime import datetime
from pathlib import Path

from .fs import atomic_write


def _git(repo_root: Path, *args: str) -> str:
    proc = subprocess.run(["git", *args], capture_output=True, text=True, cwd=repo_root)
    return proc.stdout.strip() if proc.returncode == 0 else ""


def capture(repo_root: Path) -> Path | None:
    """Capture session facts in the journal, or return None if nothing changed."""
    if not (repo_root / ".git").exists():
        return None

    journal_dir = repo_root / ".agent" / "journal"
    journal_dir.mkdir(parents=True, exist_ok=True)
    marker = journal_dir / ".last-capture"  # Runtime marker ignored by the journal.

    branch = _git(repo_root, "rev-parse", "--abbrev-ref", "HEAD") or "-"
    head = _git(repo_root, "rev-parse", "HEAD")
    dirty = _git(repo_root, "status", "--porcelain")
    last_head = marker.read_text().strip() if marker.is_file() else ""

    if head == last_head and not dirty:
        return None  # Nothing changed since the previous capture.

    if last_head:
        commits = _git(repo_root, "log", "--oneline", f"{last_head}..{head}")
    else:
        commits = _git(repo_root, "log", "--oneline", "-5")

    now = datetime.now()
    lines = [f"## {now:%H:%M} - branch {branch} @ {head[:9] or '-'}"]
    if commits:
        lines.append("commits since the previous capture:")
        lines += [f"- {c}" for c in commits.splitlines()]
    if dirty:
        files = dirty.splitlines()
        lines.append(f"uncommitted: {len(files)} files")
        lines += [f"- {f.strip()}" for f in files[:15]]
        if len(files) > 15:
            lines.append(f"- ... and {len(files) - 15} more")
    diffstat = _git(repo_root, "diff", "--shortstat")
    if diffstat:
        lines.append(f"diff: {diffstat}")
    day_file = journal_dir / f"{now:%Y-%m-%d}.md"
    new_day = not day_file.exists()
    if new_day:
        before = f"# Journal {now:%Y-%m-%d} (generated by session-capture; do not edit manually)"
    else:
        before = day_file.read_text(encoding="utf-8").rstrip()
    # Blocks use one blank separator and the file ends with exactly one LF, so
    # generated journal updates continue to pass ``git diff --check``.
    atomic_write(day_file, before + "\n\n" + "\n".join(lines) + "\n")
    marker.write_text(head)
    return day_file


def main() -> int:
    """Resolve the repository root from cwd and fall back to cwd itself.

    Always exit with 0: a broken capture must not fail the client's session end.
    """
    root = _git(Path.cwd(), "rev-parse", "--show-toplevel")
    capture(Path(root) if root else Path.cwd())
    return 0


if __name__ == "__main__":
    sys.exit(main())
